name: Deploy and Run Cypress Tests on EC2

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  deploy-test:
    name: Deploy and Run Cypress on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > automation-key.pem
          chmod 600 automation-key.pem

      - name: Run Cypress tests on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i automation-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/testing || git clone https://github.com/your-org/testing.git ~/testing && cd ~/testing

            git pull origin main
            

            docker build -t cypress-tests .
            docker run -e CYPRESS_baseUrl=http://login-app-forntend-bucket.s3-website-us-east-1.amazonaws.com \
                       -e CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }} \
                       cypress-tests
                        --record \
              --key=${{ secrets.CYPRESS_RECORD_KEY }}
          EOF
