name: Build, Analyze and Run Cypress Tests on EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-and-test:
    name: Deploy and Run Cypress Tests on EC2
    runs-on: ubuntu-latest
    needs: sonar-analysis  # Wait until Sonar analysis is complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/testing

      - name: SSH into EC2 and Run Cypress in Docker
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd /home/ubuntu/testing
            git pull origin main

            echo "Running Cypress tests inside Docker container..."

            docker build -t cypress-tests .

            docker run \
              -e CYPRESS_baseUrl=http://login-app-forntend-bucket.s3-website-us-east-1.amazonaws.com \
              -e CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }} \
              cypress-tests \
              --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
          EOF
